---
title: "Homework5"
author: "Neda Safari"
date: "`r Sys.Date()`"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, error = FALSE)
library(dplyr)
library(tidyverse)
library(readr)
library(ggplot2)
library(viridis)
```

Selected the Second Choice
    
```{r}
homicides<- read.csv("data-homicides-master/homicide-data.csv")
```
   

  
```{r}
Freddie_Gray<- homicides%>%
  filter(str_detect(victim_last, "GREY") & str_detect(victim_first, "^FREDDIE"))%>%
  pull(reported_date)

Freddie_Gray<- ymd(paste(substr(Freddie_Gray, 1, 4), substr(Freddie_Gray,5,6),"01", sep="-"))
Freddie_Gray
```
 
  
```{r}
baltimore_data<- homicides%>%
  filter(city == "Baltimore")%>%
  mutate(date_r= ymd(reported_date),
         year_month= paste(year(date_r), month(date_r), "01", sep = "-"),
         date=ymd(year_month),
         month= month (date),
         season= ifelse(month %in% c(11,12,1,2,3,4),"Winter", "Summer"))%>%
  group_by(date, season)%>%
  summarise(homicides=n(), .groups = "drop")

baltimore_data

```
    

```{r, fig.width= 10, fig.height= 3}
baltimore_data%>%
ggplot(aes(date, homicides))+
  geom_col(aes(fill=season), width= 26)+
  geom_smooth(color= "royalblue", se= FALSE, method = 'loess', span = 0.12, linewidth= 1.5)+
 geom_vline(aes(xintercept= Freddie_Gray), linetype= "dashed", color= "red", linewidth= 1.5)+
  annotate("text", Freddie_Gray, 40, label= "Arrest of \nFreddie Gray", color= "cornsilk2", hjust=1)+
  labs(title= "Homicides in Baltimore, MD", x= "Date", y="Monthly homicides")+
  scale_fill_manual(values= c("Summer"="cornsilk3", "Winter"="lightcyan3"), name=NULL)+
  theme_dark() 
```


    
    
    
    
    
    








