# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit example_r_journal.Rmd to modify this file

## ----Rlogo, echo=FALSE, fig.cap='The logo of R.', out.width='2in', fig.align='center', fig.pos='htbp'----
knitr::include_graphics('Rlogo-5.png')


## -----------------------------------------------------------------------------
x <- 1:10
plot(x)

